# Generated by Django 4.0.4 on 2022-06-30 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(through='newapp.UserSubscribe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubscribe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='usersubscribe',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя подписчика'),
        ),
    ]
