# Generated by Django 4.0.4 on 2022-06-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_usersubscribe_category_subscribe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribe',
            new_name='subscriber',
        ),
    ]
