# Generated by Django 4.0.6 on 2022-07-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_rename_subscribe_category_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscriber',
            new_name='subscribers',
        ),
        migrations.RenameField(
            model_name='usersubscribe',
            old_name='subscriber',
            new_name='subscribers',
        ),
    ]
